name: ping

on:
  schedule:
    # Run at 00, 15, 30, and 45 minutes past each hour
    # From 08:00 until 23:45 Argentina time
    - cron: '0,15,30,45 11-23,0-2 * * *'
  workflow_dispatch:

env:
  TARGET_URL: https://ndamatta.onrender.com/

jobs:
  ping-render:
    runs-on: ubuntu-latest
    env:
      TZ: America/Argentina/Buenos_Aires

    steps:
      - name: Ping Render service
        run: |
          echo "Pinging $TARGET_URL at $(date)..."
          curl -IL --fail "$TARGET_URL" || echo "Ping failed at $(date)"
